/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.CustomerGUI;

/**
 *
 * @author DUONG NGOC YEN
 */
public class Transfer_Form extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Transfer_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome_Update = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnExit_Update1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        txtID2 = new javax.swing.JTextField();
        txtName2 = new javax.swing.JTextField();
        txtAge1 = new javax.swing.JTextField();
        txtAge2 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        btnAdd3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 250, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome_Update.setBackground(new java.awt.Color(32, 172, 216));
        btnHome_Update.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnHome_Update.setForeground(new java.awt.Color(255, 255, 255));
        btnHome_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/home_25px.png"))); // NOI18N
        btnHome_Update.setText("Home");
        btnHome_Update.setToolTipText("");
        btnHome_Update.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome_Update.setIconTextGap(1);
        btnHome_Update.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(32, 172, 216));
        jLabel25.setText("Ngân hàng");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 129, -1, 32));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(32, 172, 216));
        jLabel16.setText("Số tài khoản");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 178, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(32, 172, 216));
        jLabel17.setText("Tên người nhận");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 223, -1, 37));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(32, 172, 216));
        jLabel29.setText("Số tiền");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 288, -1, -1));

        btnExit_Update1.setBackground(new java.awt.Color(32, 172, 216));
        btnExit_Update1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExit_Update1.setForeground(new java.awt.Color(255, 255, 255));
        btnExit_Update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/shutdown_20px.png"))); // NOI18N
        btnExit_Update1.setText("Logout");
        btnExit_Update1.setToolTipText("");
        btnExit_Update1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit_Update1.setIconTextGap(0);
        btnExit_Update1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnExit_Update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, 50));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(32, 172, 216));
        jLabel30.setText("Phí");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 331, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(32, 172, 216));
        jLabel31.setText("Nội dung");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 374, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACB Bank", "ViettinBank", "VietComBank", "VP Bank", "SacomBank", "MB Bank", "TechcomBank", " " }));
        jComboBox3.setSelectedIndex(-1);
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 130, 355, 32));

        txtID2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 178, 207, 32));

        txtName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 230, 360, 32));

        txtAge1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 288, 310, 32));

        txtAge2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAge2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtAge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 338, 140, 32));

        txtAddress2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 388, 360, 88));

        btnAdd3.setBackground(new java.awt.Color(32, 172, 216));
        btnAdd3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd3.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd3.setText("Tiếp tục");
        jPanel1.add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 527, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("VND");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("VND");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/bank_building_30px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 134, 40, 30));

        jLabel7.setBackground(new java.awt.Color(32, 172, 216));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("                  Transfer");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(34, 50));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress2ActionPerformed

    private void btnHome_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_UpdateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnHome_UpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnExit_Update1;
    private javax.swing.JButton btnHome_Update;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtAge2;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtName2;
    // End of variables declaration//GEN-END:variables
}
